routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('posts', 'PostController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'slug',
        'content',
    ];

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::orderby('created_at', 'desc')->paginate(10);

        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title'   => 'required|string|unique:posts,title',
            'content' => 'required|string|min:5|max:1000',
        ]);

        Post::create([
            'title'   => title_case($request->title),
            'slug'    => str_slug($request->title),
            'content' => title_case($request->content),
        ]);

        return redirect()->route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $request->validate([
            'title'   => 'required|string|unique:posts,title,'.$post->id,
            'content' => 'required|string|min:5|max:1000',
        ]);

        $post->update([
            'title'   => title_case($request->title),
            'slug'    => str_slug($request->title),
            'content' => title_case($request->content),
        ]);

        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();

        return redirect()->route('posts.index');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title', config('app.name', 'My Blog'))</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500,500i,700,900" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <li><a class="nav-link" href="{{ route('posts.index') }}">Blog</a></li>

                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li><a class="nav-link" href="{{ route('posts.create') }}">Create Post</a></li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('title', 'Create Post')

@section('content')
    <div class="container">
        <form method="POST" action="{{ route('posts.store') }}" role="form">

            @csrf

            {{-- Post Title --}}
            <div class="form-group">
                <label for="title">Post Title</label>

                <input class="form-control{{ $errors->has('title') ? ' is-invalid' : null }}" type="text" name="title" id="title" placeholder="Post title" value="{{ old('title') }}" autofocus>

                @if ($errors->has('title'))
                    <div class="text-danger">{{ $errors->first('title') }}</div>
                @endif
            </div>

            {{-- Post Content --}}
            <div class="form-group">
                <label for="content">Post Content</label>

                <textarea class="form-control{{ $errors->has('content') ? ' is-invalid' : null }}" name="content" id="content" rows="5" placeholder="Post content">{{ old('content') }}</textarea>

                @if ($errors->has('content'))
                    <div class="text-danger">{{ $errors->first('content') }}</div>
                @endif
            </div>

            {{-- Button to submit the form --}}
            <input class="btn btn-primary" type="submit" value="Create Post">
        </form>
    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Post')

@section('content')
    <div class="container">
        <form method="POST" action="{{ route('posts.update', $post->slug) }}" role="form">

            @csrf

            @method('PATCH')

            {{-- Post Title --}}
            <div class="form-group">
                <label for="title">Post Title</label>

                <input class="form-control{{ $errors->has('title') ? ' is-invalid' : null }}" type="text" name="title" id="title" placeholder="Post title" value="{{ old('title', $post->title) }}" autofocus
                >

                @if ($errors->has('title'))
                    <div class="text-danger">{{ $errors->first('title') }}</div>
                @endif
            </div>

            {{-- Post Content --}}
            <div class="form-group">
                <label for="content">Post Content</label>

                <textarea class="form-control{{ $errors->has('content') ? ' is-invalid' : null }}" name="content" id="content" rows="5" placeholder="Post content">{{ old('content', $post->content) }}</textarea>

                @if ($errors->has('content'))
                    <div class="text-danger">{{ $errors->first('content') }}</div>

                @endif
            </div>

            {{-- Button to submit the form --}}
            <input class="btn btn-info" type="submit" value="Update Post">
        </form>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('title', 'Blog')

@section('content')
    <div class="container">
        @if (!$posts->count())
            <div class="text-center">
                <h3>It's empty here!</h3>

                @auth
                    <a class="btn btn-info" href="{{ route('posts.create') }}">Create Post</a>
                @endauth
            </div>
        @else
            <ul class="list-group">
                @foreach ($posts as $post)
                    <li class="list-group-item">

                        {{-- Only logged in users can edit and delete the posts --}}

                        @auth
                            <div class="d-inline pr-3">
                                {{-- Edit Post --}}
                                <a class="btn btn-primary btn-sm" href="{{ route('posts.edit', $post->slug) }}">
                                    <i class="fa fa-pencil"></i>
                                </a>

                                {{-- Delete Post --}}
                                <form class="d-inline" method="POST" action="{{ route('posts.destroy', $post->slug) }}" onsubmit="if (!confirm('Are you sure to delete this post?')) { return false; }">

                                    @csrf

                                    @method('DELETE')

                                    <button class="btn btn-danger btn-sm">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </form>
                            </div>
                        @endauth

                        {{-- Post Created Time --}}
                        <div class="d-inline">
                            <i class="fa fa-clock-o"></i>

                            <span class="text-muted">
                                {{ \Carbon\Carbon::parse($post->created_at)->diffForHumans() }}
                            </span>
                        </div>

                        {{-- Post Title --}}
                        <h1 class="h6 d-inline pl-3">
                            <a href="{{ route('posts.show', ['post' => $post->slug]) }}">
                                {{ $post->title }}
                            </a>
                        </h1>

                        {{-- Post Content --}}
                        <p class="text-muted pt-3">
                            {{ str_limit($post->content, 150) }}  
                        </p>
                    </li>
                @endforeach
            </ul>

            {{-- Pagination Links --}}
            <div class="my-3">
                {{ $posts->links() }}
            </div>
        @endif
    </div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('title', $post->title)

@section('content')
    <div class="container bg-white p-5 shadow-sm">
        {{-- Post Created Time --}}
        <div class="d-inline">
            <i class="fa fa-calendar"></i>
            <span class="text-muted">
                {{ \Carbon\Carbon::parse($post->created_at)->format("D, dS M'y") }}
            </span>
        </div>

        {{-- Post Title --}}
        <h1 class="h3 pt-4">
            {{ $post->title }}
        </h1>

        {{-- Post Content --}}
        <p class="text-muted pt-3">
            {{ $post->content }}  
        </p>
    </div>
@endsection